runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /test.*
  script: gaeunit/gaeunit.py

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /static/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  secure: always
  redirect_http_response_code: 301

- url: /static/*
  static_dir: static
  expiration: '0'
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: djangoappengine/main/main.py
  secure: always
  redirect_http_response_code: 301

