application: bingo-board-hrd
version: 3
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /test.*
  script: gaeunit/gaeunit.py

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /static/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

# Next 3 lines must be uncommented before deployment
# - url: /static/*
#  static_dir: static
#  expiration: '0'

- url: /.*
  script: djangoappengine/main/main.py

